export const COMMUNES_BY_WILAYA: Record<number, string[]> = {
  "1": [
    "Timekten",
    "Bouda",
    "Ouled Ahmed Timmi",
    "Adrar",
    "Fenoughil",
    "In Zghmir",
    "Reggane",
    "Sali",
    "Sebaa",
    "Tsabit",
    "Tamest",
    "Tamantit",
    "Tit",
    "Zaouiet Kounta",
    "Akabli",
    "Aoulef"
  ],
  "2": [
    "Talassa",
    "Zeboudja",
    "El Hadjadj",
    "Ouled Ben Abdelkader",
    "Ain Merane",
    "Breira",
    "Ouled Abbes",
    "Oued Fodda",
    "Beni Rached",
    "Herenfa",
    "Tadjena",
    "El Marsa",
    "Chlef",
    "Oum Drou",
    "Sendjas",
    "Sidi Abderrahmane",
    "Sidi Akkacha",
    "Tenes",
    "Beni  Bouattab",
    "El Karimia",
    "Harchoun",
    "Bouzeghaia",
    "Taougrit",
    "Beni Haoua",
    "Abou El Hassane",
    "Oued Goussine",
    "Chettia",
    "Moussadek",
    "Ouled Fares",
    "Boukadir",
    "Oued Sly",
    "Sobha",
    "Benairia",
    "Labiod Medjadja",
    "Dahra"
  ],
  "3": [
    "Tadjemout",
    "Tadjrouna",
    "Laghouat",
    "Ksar El Hirane",
    "El Assafia",
    "Sidi Makhlouf",
    "Hassi Delaa",
    "Hassi R'mel",
    "Ain Madhi",
    "El Haouaita",
    "Kheneg",
    "Benacer Benchohra"
  ],
  "4": [
    "Fkirina",
    "El Fedjoudj Boughrara Sa",
    "Ain Fekroun",
    "Rahia",
    "Meskiana",
    "El Belala",
    "Behir Chergui",
    "Ksar Sbahi",
    "Souk Naamane",
    "Ouled Zouai",
    "Oum El Bouaghi",
    "Ain Babouche",
    "Ain Zitoun",
    "Bir Chouhada",
    "Ain Beida",
    "Berriche",
    "Zorg",
    "Ain M'lila",
    "Ouled Gacem",
    "Ouled Hamla",
    "El Amiria",
    "Sigus",
    "Oued Nini",
    "Ain Diss",
    "Dhalaa",
    "El Djazia",
    "Ain Kercha",
    "El Harmilia",
    "Hanchir Toumghani"
  ],
  "5": [
    "Maafa",
    "Gosbat",
    "Timgad",
    "Taxlent",
    "Ouled Si Slimane",
    "Lemcene",
    "Talkhamt",
    "Ras El Aioun",
    "Rahbat",
    "Ouled Sellem",
    "Guigba",
    "Teniet El Abed",
    "Batna",
    "Fesdis",
    "Oued Chaaba",
    "Hidoussa",
    "Ksar Bellezma",
    "Merouana",
    "Oued El Ma",
    "Lazrou",
    "Seriana",
    "Zanet El Beida",
    "Menaa",
    "Tigharghar",
    "Ain Yagout",
    "Boumia",
    "Djerma",
    "El Madher",
    "Ouyoun El Assafir",
    "Tazoult",
    "Boumagueur",
    "N Gaous",
    "Sefiane",
    "Arris",
    "Tighanimine",
    "Ain Djasser",
    "El Hassi",
    "Foum Toub",
    "Ichemoul",
    "Inoughissen",
    "Bouzina",
    "Larbaa",
    "Boulhilat",
    "Chemora",
    "Ghassira",
    "Kimmel",
    "T Kout",
    "Ain Touta",
    "Beni Foudhala El Hakania",
    "Ouled Fadel",
    "Ouled Aouf",
    "Chir",
    "Oued Taga"
  ],
  "6": [
    "Sidi Ayad",
    "Barbacha",
    "Leflaye",
    "Kendira",
    "Sidi-Aich",
    "Tifra",
    "Tinebdar",
    "El Kseur",
    "Fenaia Il Maten",
    "Toudja",
    "Dra El Caid",
    "Kherrata",
    "Bejaia",
    "Oued Ghir",
    "Benimaouche",
    "Beni Djellil",
    "Feraoun",
    "Smaoun",
    "Timezrit",
    "Melbou",
    "Souk El Tenine",
    "Tamridjet",
    "Boukhelifa",
    "Tala Hamza",
    "Tichy",
    "Ait R'zine",
    "Ighil-Ali",
    "Ait-Smail",
    "Darguina",
    "Taskriout",
    "Aokas",
    "Tizi-N'berber",
    "Adekar",
    "Beni K'sila",
    "Taourit Ighil",
    "Akbou",
    "Chellata",
    "Ighram",
    "Tamokra",
    "Amalou",
    "Bouhamza",
    "M'cisna",
    "Seddouk",
    "Beni-Mallikeche",
    "Boudjellil",
    "Tazmalt",
    "Akfadou",
    "Chemini",
    "Souk Oufella",
    "Tibane",
    "Ouzellaguen",
    "Amizour"
  ],
  "7": [
    "El Feidh",
    "Lichana",
    "Bouchakroun",
    "Mekhadma",
    "Khenguet Sidi Nadji",
    "Zeribet El Oued",
    "Meziraa",
    "Biskra",
    "El Hadjab",
    "M'lili",
    "Foughala",
    "El Ghrous",
    "Bordj Ben Azzouz",
    "Ourlal",
    "Oumache",
    "Ain Naga",
    "Chetma",
    "El Haouch",
    "Sidi Okba",
    "M'chouneche",
    "Lioua",
    "Tolga"
  ],
  "8": [
    "Bechar",
    "Boukais",
    "Lahmar",
    "Mogheul",
    "Meridja",
    "Taghit",
    "Abadla",
    "Erg-Ferradj",
    "Machraa-Houari-Boumediene",
    "Beni-Ounif",
    "Tabelbala",
    "Kenadsa"
  ],
  "9": [
    "Beni Mered",
    "Ouled Slama",
    "Mouzaia",
    "Hammam Elouane",
    "Bougara",
    "Souhane",
    "Larbaa",
    "Soumaa",
    "Guerrouaou",
    "Boufarik",
    "Meftah",
    "Chiffa",
    "Ain Romana",
    "Oued  Djer",
    "El-Affroun",
    "Ouled Yaich",
    "Chrea",
    "Djebabra",
    "Oued El Alleug",
    "Benkhelil",
    "Beni-Tamou",
    "Chebli",
    "Bouinan",
    "Bouarfa",
    "Blida"
  ],
  "10": [
    "Ain Laloui",
    "Hadjera Zerga",
    "Mezdour",
    "Taguedite",
    "Ridane",
    "Maamora",
    "El-Hakimia",
    "Ahl El Ksar",
    "Dirah",
    "Dechmia",
    "Bechloul",
    "Ath Mansour",
    "Saharidj",
    "El Adjiba",
    "El Asnam",
    "M Chedallah",
    "Bordj Okhriss",
    "Sour El Ghozlane",
    "Hanif",
    "Chorfa",
    "Ouled Rached",
    "Ain El Hadjar",
    "Aghbalou",
    "Raouraoua",
    "El Khabouzia",
    "Bir Ghbalou",
    "Bouira",
    "Ain Turk",
    "Ait Laaziz",
    "Ain-Bessem",
    "El-Mokrani",
    "Souk El Khemis",
    "Aomar",
    "Djebahia",
    "El Hachimia",
    "Haizer",
    "Taghzout",
    "Bouderbala",
    "Boukram",
    "Guerrouma",
    "Lakhdaria",
    "Maala",
    "Kadiria",
    "Z'barbar (El Isseri )",
    "Oued El Berdi"
  ],
  "11": [
    "Tazrouk",
    "Abelsa",
    "Tamanrasset",
    "Ain Amguel",
    "Idles"
  ],
  "12": [
    "El-Houidjbet",
    "El-Aouinet",
    "Bir Mokkadem",
    "Bir Dheheb",
    "Saf Saf El Ouesra",
    "Guorriguer",
    "Bekkaria",
    "Boulhaf Dyr",
    "Oum Ali",
    "Boukhadra",
    "El Malabiod",
    "Ouenza",
    "El Meridj",
    "Ain Zerga",
    "Stah Guentis",
    "El Ogla",
    "El Mezeraa",
    "Bedjene",
    "Morsott",
    "Telidjen",
    "Cheria",
    "Tebessa",
    "Hammamet",
    "El Kouif"
  ],
  "13": [
    "Bab El Assa",
    "Terny Beni Hediel",
    "Mansourah",
    "Beni Mester",
    "Ain Ghoraba",
    "Chetouane",
    "Amieur",
    "Ain Fezza",
    "Honnaine",
    "Beni Khellad",
    "Nedroma",
    "M'sirda Fouaga",
    "Marsa Ben M'hidi",
    "Sidi Medjahed",
    "Beni Boussaid",
    "Sebdou",
    "Bouhlou",
    "Maghnia",
    "Hammam Boughrara",
    "Zenata",
    "Ouled Riyah",
    "Hennaya",
    "Sidi Abdelli",
    "Souk Tleta",
    "Bensekrane",
    "Fellaoucene",
    "Ain Kebira",
    "Ain Fetah",
    "Tlemcen",
    "Ain Nehala",
    "Ain Tellout",
    "Ain Youcef",
    "Beni Ouarsous",
    "El Fehoul",
    "Remchi",
    "Sebbaa Chioukh",
    "Souani",
    "Sabra",
    "Dar Yaghmoracen",
    "Ghazaouet",
    "Souahlia",
    "Tianet",
    "Beni Smiel",
    "Oued Lakhdar",
    "Ouled Mimoun",
    "Beni Bahdel",
    "Beni Snous",
    "Azail",
    "Djebala"
  ],
  "14": [
    "Mahdia",
    "Ain Dzarit",
    "Sebaine",
    "Faidja",
    "Si Abdelghani",
    "Sougueur",
    "Tousnina",
    "Meghila",
    "Sebt",
    "Sidi Hosni",
    "Ain El Hadid",
    "Frenda",
    "Takhemaret",
    "Ain Kermes",
    "Djebilet Rosfa",
    "Madna",
    "Medrissa",
    "Sidi Abderrahmane",
    "Guertoufa",
    "Oued Lilli",
    "Sidi Ali Mellal",
    "Djillali Ben Amar",
    "Mechraa Safa",
    "Tagdempt",
    "Tidda",
    "Nadorah",
    "Tiaret",
    "Medroussa",
    "Mellakou",
    "Sidi Bakhti",
    "Ain Deheb",
    "Chehaima",
    "Naima",
    "Ain Bouchekif",
    "Dahmouni",
    "Rahouia"
  ],
  "15": [
    "Mizrana",
    "Idjeur",
    "Beni-Douala",
    "Beni-Zikki",
    "Illoula Oumalou",
    "Agouni-Gueghrane",
    "Ait Bouaddou",
    "Ouadhias",
    "Tizi N'tleta",
    "Aghribs",
    "Ait-Chafaa",
    "Akerrou",
    "Azeffoun",
    "Iflissen",
    "Tigzirt",
    "Assi-Youcef",
    "Boghni",
    "Bounouh",
    "Mechtras",
    "Draa-Ben-Khedda",
    "Sidi Namane",
    "Tadmait",
    "Tirmitine",
    "Ait Boumahdi",
    "Ait-Toudert",
    "Beni-Aissi",
    "Ouacif",
    "Ait Khellili",
    "Mekla",
    "Souama",
    "Beni-Yenni",
    "Iboudrarene",
    "Tizi-Ouzou",
    "Abi-Youcef",
    "Ain-El-Hammam",
    "Ait-Yahia",
    "Akbil",
    "Boudjima",
    "Makouda",
    "Ain-Zaouia",
    "Ait Yahia Moussa",
    "Draa-El-Mizan",
    "Frikat",
    "M'kira",
    "Tizi-Gheniff",
    "Yatafene",
    "Illilten",
    "Imsouhal",
    "Azazga",
    "Freha",
    "Ifigha",
    "Yakourene",
    "Zekri",
    "Ait Aggouacha",
    "Irdjen",
    "Larbaa Nath Irathen",
    "Ait-Oumalou",
    "Tizi-Rached",
    "Ait-Aissa-Mimoun",
    "Ouaguenoun",
    "Timizart",
    "Maatkas",
    "Souk-El-Tenine",
    "Ait-Mahmoud",
    "Beni Zmenzer",
    "Iferhounene",
    "Bouzeguene"
  ],
  "16": [
    "Hussein Dey",
    "Les Eucalyptus",
    "Sidi Moussa",
    "Kouba",
    "Mohamed Belouzdad",
    "Ain Taya",
    "Bab Ezzouar",
    "Bordj El Kiffan",
    "Dar El Beida",
    "El Marsa",
    "Mohammadia",
    "Bir Touta",
    "Ouled Chebel",
    "Tessala El Merdja",
    "Herraoua",
    "Reghaia",
    "Rouiba",
    "Maalma",
    "Rahmania",
    "Souidania",
    "Staoueli",
    "Zeralda",
    "Baba Hassen",
    "Douira",
    "Draria",
    "El Achour",
    "Khraissia",
    "Ain Benian",
    "Cheraga",
    "Dely Ibrahim",
    "Hammamet",
    "Ouled Fayet",
    "Alger Centre",
    "El Madania",
    "El Mouradia",
    "Sidi M'hamed",
    "Sehaoula",
    "Bologhine Ibnou Ziri",
    "Casbah",
    "Oued Koriche",
    "Rais Hamidou",
    "Bir Mourad Rais",
    "Birkhadem",
    "Djasr Kasentina",
    "Hydra",
    "El Magharia",
    "Ben Aknoun",
    "Beni Messous",
    "Bouzareah",
    "El Biar",
    "Bachedjerah",
    "Bourouba",
    "El Harrach",
    "Oued Smar",
    "Baraki",
    "Bordj El Bahri",
    "Bab El Oued"
  ],
  "17": [
    "Hassi El Euch",
    "Ain El Ibel",
    "El Guedid",
    "Charef",
    "Benyagoub",
    "Sidi Baizid",
    "M'liliha",
    "Dar Chioukh",
    "Taadmit",
    "Zaccar",
    "Douis",
    "El Idrissia",
    "Ain Chouhada",
    "Djelfa",
    "Zaafrane",
    "Ain Maabed",
    "Hassi Bahbah",
    "Moudjebara"
  ],
  "18": [
    "Jijel",
    "El Aouana",
    "Selma Benziada",
    "Erraguene Souissi",
    "Boussif Ouled Askeur",
    "Ziama Mansouriah",
    "Chahna",
    "Emir Abdelkader",
    "Oudjana",
    "Taher",
    "Chekfa",
    "El Kennar Nouchfi",
    "Sidi Abdelaziz",
    "El Milia",
    "Ouled Yahia Khadrouch",
    "Ouled Rabah",
    "Sidi Marouf",
    "Ghebala",
    "Settara",
    "Bouraoui Belhadef",
    "El Ancer",
    "Khiri Oued Adjoul",
    "Djimla",
    "Kaous",
    "Texenna",
    "Bordj T'har",
    "Boudria Beniyadjis",
    "Djemaa Beni Habibi"
  ],
  "19": [
    "Rosfa",
    "Oued El Bared",
    "Tizi N'bechar",
    "Mezloug",
    "Guellal",
    "Kasr El Abtal",
    "Ouled Si Ahmed",
    "Ait Naoual Mezada",
    "Ait-Tizi",
    "Bouandas",
    "Bousselam",
    "Hamam Soukhna",
    "Taya",
    "Tella",
    "Ain Oulmene",
    "Boutaleb",
    "Hamma",
    "Ouled Tebben",
    "Amoucha",
    "Salah Bey",
    "Ain Azel",
    "Ain Lahdjar",
    "Beidha Bordj",
    "Bir Haddada",
    "Guenzet",
    "Harbil",
    "Ain-Roua",
    "Beni Oussine",
    "El Ouricia",
    "Bougaa",
    "Draa-Kebila",
    "Hammam Guergour",
    "Setif",
    "Ain El Kebira",
    "Dehamcha",
    "Ouled Addouane",
    "Ain-Sebt",
    "Beni-Aziz",
    "Maaouia",
    "Bellaa",
    "Bir-El-Arch",
    "El-Ouldja",
    "Tachouda",
    "Tala-Ifacene",
    "Serdj-El-Ghoul",
    "Guidjel",
    "Ouled Sabor",
    "Bazer-Sakra",
    "El Eulma",
    "Guelta Zerka",
    "Beni Fouda",
    "Djemila",
    "Ain-Legradj",
    "Beni Chebana",
    "Beni Ourtilane",
    "Beni-Mouhli",
    "Ain Abessa",
    "Ain Arnat",
    "Babor",
    "Maouaklane"
  ],
  "20": [
    "Saida",
    "Tircine",
    "Ouled Brahim",
    "Ain Soltane",
    "Maamora",
    "El Hassasna",
    "Ain Sekhouna",
    "Sidi Boubekeur",
    "Ouled Khaled",
    "Hounet",
    "Youb",
    "Doui Thabet",
    "Sidi Ahmed",
    "Moulay Larbi",
    "Ain El Hadjar",
    "Sidi Amar"
  ],
  "21": [
    "Ain Bouziane",
    "Salah Bouchaour",
    "El Hadaiek",
    "Zerdezas",
    "Ouled Habbaba",
    "Beni Oulbane",
    "Sidi Mezghiche",
    "Beni Bechir",
    "Ramdane Djamel",
    "Bin El Ouiden",
    "Emjez Edchich",
    "Tamalous",
    "Ain Kechra",
    "Ouldja Boulbalout",
    "Oum Toub",
    "El Ghedir",
    "Kerkara",
    "El Arrouch",
    "Zitouna",
    "Ouled Attia",
    "Oued Zhour",
    "Collo",
    "Cheraia",
    "Beni Zid",
    "Khenag Maoune",
    "El Marsa",
    "Ben Azzouz",
    "Bekkouche Lakhdar",
    "Es Sebt",
    "Ain Charchar",
    "Azzaba",
    "Bouchetata",
    "Filfila",
    "Hammadi Krouma",
    "Skikda",
    "Ain Zouit",
    "Djendel Saadi Mohamed",
    "Kanoua"
  ],
  "22": [
    "Sidi Ali Benyoub",
    "Moulay Slissen",
    "El Hacaiba",
    "Ain Tindamine",
    "Tenira",
    "Oued Sefioun",
    "Hassi Dahou",
    "Oued Taourira",
    "Benachiba Chelia",
    "Sidi Yacoub",
    "Sidi Lahcene",
    "Sidi Khaled",
    "Tabia",
    "Sidi Brahim",
    "Amarnas",
    "Boukhanefis",
    "Hassi Zahana",
    "Chetouane Belaila",
    "Ben Badis",
    "Bedrabine El Mokrani",
    "Sfisef",
    "M'cid",
    "Boudjebaa El Bordj",
    "Ain- Adden",
    "Sidi Hamadouche",
    "Sidi Chaib",
    "Makedra",
    "Ain El Berd",
    "Redjem Demouche",
    "Ras El Ma",
    "Oued Sebaa",
    "Marhoum",
    "Sidi Bel-Abbes",
    "Ain Thrid",
    "Sehala Thaoura",
    "Tessala",
    "Belarbi",
    "Mostefa  Ben Brahim",
    "Tilmouni",
    "Zerouala",
    "Dhaya",
    "Mezaourou",
    "Teghalimet",
    "Telagh",
    "Ain Kada",
    "Lamtar",
    "Sidi Ali Boussidi",
    "Sidi Dahou Zairs",
    "Bir El Hammam",
    "Merine",
    "Tefessour",
    "Taoudmout"
  ],
  "23": [
    "Annaba",
    "Seraidi",
    "Berrahal",
    "Oued El Aneb",
    "El Hadjar",
    "Sidi Amar",
    "El Bouni",
    "Ain El Berda",
    "Cheurfa",
    "El Eulma",
    "Treat",
    "Chetaibi"
  ],
  "24": [
    "Nechmaya",
    "Bou Hamdane",
    "Hammam Debagh",
    "Roknia",
    "Dahouara",
    "Hammam N'bail",
    "Guelma",
    "Boumahra Ahmed",
    "Ain Ben Beida",
    "Bouchegouf",
    "Medjez Sfa",
    "Oued Ferragha",
    "Bouati Mahmoud",
    "El Fedjoudj",
    "Heliopolis",
    "Medjez Amar",
    "Houari Boumedienne",
    "Ras El Agba",
    "Sellaoua Announa",
    "Djeballah Khemissi",
    "Bordj Sabath",
    "Oued Zenati",
    "Ain Regada",
    "Ain Larbi",
    "Ain Makhlouf",
    "Tamlouka",
    "Ain Sandel",
    "Bou Hachana",
    "Khezaras",
    "Belkheir",
    "Beni Mezline",
    "Guelaat Bou Sbaa",
    "Oued Cheham",
    "Bendjarah"
  ],
  "25": [
    "Didouche Mourad",
    "Hamma Bouziane",
    "Beni Hamidane",
    "Zighoud Youcef",
    "Ain Smara",
    "El Khroub",
    "Ouled Rahmoun",
    "Ain Abid",
    "Ben Badis",
    "Ibn Ziad",
    "Messaoud Boudjeriou",
    "Constantine"
  ],
  "26": [
    "Souagui",
    "El Azizia",
    "Maghraoua",
    "Mihoub",
    "Hannacha",
    "Ouamri",
    "Oued Harbil",
    "Beni Slimane",
    "Bouaichoune",
    "Ouled Bouachra",
    "Si Mahdjoub",
    "Bouskene",
    "Sidi Rabie",
    "Berrouaghia",
    "Ouled Deid",
    "Rebaia",
    "Medjebar",
    "Tletat Ed Douair",
    "Zoubiria",
    "Aissaouia",
    "El Haoudane",
    "Mezerana",
    "Tablat",
    "Seghouane",
    "Draa Esmar",
    "Medea",
    "Tamesguida",
    "Ben Chicao",
    "El Hamdania",
    "Ouzera",
    "Tizi Mahdi",
    "Baata",
    "El Omaria",
    "Ouled Brahim",
    "Bir Ben Laabed",
    "El Guelbelkebir",
    "Sedraya",
    "Bouchrahil",
    "Khams Djouamaa",
    "Sidi Naamane",
    "Djouab",
    "Sidi Zahar",
    "Sidi Ziane"
  ],
  "27": [
    "Fornaka",
    "Oued El Kheir",
    "Hassiane",
    "Hassi Mameche",
    "Mazagran",
    "Stidia",
    "Ain-Tedles",
    "Sidi Belaattar",
    "Sour",
    "Ain-Boudinar",
    "Kheir-Eddine",
    "Sayada",
    "Sidi Ali",
    "Tazgait",
    "Benabdelmalek Ramdane",
    "Mostaganem",
    "Hadjadj",
    "Sidi-Lakhdar",
    "Achaacha",
    "Khadra",
    "Nekmaria",
    "Ouled Boughalem",
    "Bouguirat",
    "Safsaf",
    "Sirat",
    "Souaflia",
    "Ain-Sidi Cherif",
    "Mansourah",
    "Mesra",
    "Touahria",
    "Ain-Nouissy",
    "Ouled-Maalah"
  ],
  "28": [
    "Chellal",
    "Ouled Madhi",
    "Khettouti Sed-El-Jir",
    "Belaiba",
    "Berhoum",
    "Dehahna",
    "Magra",
    "Beni Ilmane",
    "Bouti Sayeh",
    "Sidi Aissa",
    "Ain El Hadjel",
    "Djebel Messaad",
    "M'sila",
    "Hammam Dalaa",
    "Ouanougha",
    "Ouled Mansour",
    "Tarmount",
    "Ouled Derradj",
    "Souamaa",
    "El Houamed",
    "Khoubana",
    "M'cif",
    "Ain Khadra",
    "Ouled Addi Guebala"
  ],
  "29": [
    "Oued El Abtal",
    "Sidi Abdelmoumene",
    "Sedjerara",
    "Mohammadia",
    "Tighennif",
    "Mocta-Douz",
    "Ferraguig",
    "El Ghomri",
    "Zahana",
    "El Gaada",
    "Ras El Ain Amirouche",
    "Oggaz",
    "Alaimia",
    "Sig",
    "Chorfa",
    "Bou Henni",
    "El Mamounia",
    "El Gueitena",
    "Ain Fares",
    "Gharrous",
    "Benian",
    "Aouf",
    "Guerdjoum",
    "Ain Frass",
    "Ain Fekan",
    "Khalouia",
    "El Menaouer",
    "El Bordj",
    "Sidi Boussaid",
    "Matemore",
    "Sidi Kada",
    "Makhda",
    "Mascara",
    "Bouhanifia",
    "Ghriss",
    "Hacine",
    "El Keurt",
    "Froha",
    "Tizi",
    "Sehailia",
    "Maoussa",
    "Sidi Abdeldjebar",
    "El Hachem",
    "Nesmot",
    "Zelamta",
    "Ain Ferah",
    "Oued Taria"
  ],
  "30": [
    "Ouargla",
    "Hassi Messaoud",
    "Ain Beida",
    "Hassi Ben Abdellah",
    "Sidi Khouiled",
    "El Borma",
    "Rouissat",
    "N'goussa"
  ],
  "31": [
    "Sidi Chami",
    "Hassi Mefsoukh",
    "Bir El Djir",
    "Hassi Ben Okba",
    "Gdyel",
    "Hassi Bounif",
    "El Kerma",
    "Es Senia",
    "Ben Freha",
    "Arzew",
    "Sidi Ben Yebka",
    "Ain Biya",
    "Bethioua",
    "Marsat El Hadjadj",
    "Ain Turk",
    "Oran",
    "El Ancor",
    "Mers El Kebir",
    "Boufatis",
    "El Braya",
    "Oued Tlelat",
    "Ain Kerma",
    "Boutlelis",
    "Messerghin",
    "Bousfer",
    "Tafraoui"
  ],
  "32": [
    "Ain El Orak",
    "Krakda",
    "Sidi Slimane",
    "Sidi Ameur",
    "Boualem",
    "El Bnoud",
    "Bougtoub",
    "El Kheiter",
    "Tousmouline",
    "Sidi Tiffour",
    "Stitten",
    "El Bayadh",
    "Rogassa",
    "El Mehara",
    "Kef El Ahmar"
  ],
  "33": [
    "Bordj Omar Driss",
    "Debdeb",
    "In Amenas",
    "Illizi"
  ],
  "34": [
    "Elhammadia",
    "Ouled Sidi-Brahim",
    "Ain Taghrout",
    "Tixter",
    "Belimour",
    "El Annasseur",
    "Ghailasa",
    "Taglait",
    "Bordj Ghedir",
    "El Euch",
    "Sidi-Embarek",
    "Khelil",
    "Bir Kasdali",
    "Tefreg",
    "El Main",
    "Djaafra",
    "Colla",
    "Teniet En Nasr",
    "El M'hir",
    "Ksour",
    "Mansoura",
    "Haraza",
    "Rabta",
    "El Achir",
    "Hasnaoua",
    "Medjana",
    "Ain Tesra",
    "Ouled Brahem",
    "Ras El Oued",
    "Bordj Zemmoura",
    "Ouled Dahmane",
    "Tassamert",
    "B. B. Arreridj",
    "Ben Daoud"
  ],
  "35": [
    "El Kharrouba",
    "Dellys",
    "Ben Choud",
    "Afir",
    "Thenia",
    "Beni Amrane",
    "Khemis El Khechna",
    "Ammal",
    "Timezrit",
    "Zemmouri",
    "Larbatache",
    "Isser",
    "Chabet El Ameur",
    "Ouled Aissa",
    "Naciria",
    "Bouzegza Keddara",
    "Souk El Had",
    "Sidi Daoud",
    "Baghlia",
    "Leghata",
    "Djinet",
    "Tidjelabine",
    "Si Mustapha",
    "Ouled Hedadj",
    "Ouled Moussa",
    "Boumerdes",
    "Corso",
    "Bordj Menaiel",
    "Boudouaou",
    "Boudouaou El Bahri",
    "Taourga",
    "Hammedi"
  ],
  "36": [
    "Ain El Assel",
    "Bougous",
    "El Tarf",
    "Zitouna",
    "Besbes",
    "Ain Kerma",
    "Bouhadjar",
    "Hammam Beni Salah",
    "Oued Zitoun",
    "Ben M Hidi",
    "Berrihane",
    "Chebaita Mokhtar",
    "Echatt",
    "El Aioun",
    "El Kala",
    "Souarekh",
    "Zerizer",
    "Bouteldja",
    "Chefia",
    "Lac Des Oiseaux",
    "Chihani",
    "Raml Souk",
    "Asfour",
    "Drean"
  ],
  "37": [
    "Tindouf",
    "Oum El Assel"
  ],
  "38": [
    "Khemisti",
    "Theniet El Had",
    "Ouled Bessam",
    "Sidi Boutouchent",
    "Tissemsilt",
    "Sidi Lantri",
    "Beni Chaib",
    "Beni Lahcene",
    "Sidi Abed",
    "Sidi Slimane",
    "Boucaid",
    "Larbaa",
    "Lazharia",
    "Lardjem",
    "Melaab",
    "Layoune",
    "Tamellahet",
    "Youssoufia",
    "Bordj El Emir Abdelkader",
    "Ammari",
    "Maacem",
    "Bordj Bounaama"
  ],
  "39": [
    "Douar El Maa",
    "El Ogla",
    "Magrane",
    "Sidi Aoun",
    "Mih Ouansa",
    "Kouinine",
    "Bayadha",
    "Nakhla",
    "Robbah",
    "Guemar",
    "Ben Guecha",
    "Ourmes",
    "Taghzout",
    "Hamraia",
    "Reguiba",
    "Debila",
    "Hassani Abdelkrim",
    "Hassi Khalifa",
    "Trifaoui",
    "Taleb Larbi",
    "Oued El Alenda",
    "El-Oued"
  ],
  "40": [
    "Khirane",
    "Babar",
    "El Mahmal",
    "Ouled Rechache",
    "Djellal",
    "Yabous",
    "Khenchela",
    "Kais",
    "Chelia",
    "Remila",
    "Taouzianat",
    "Baghai",
    "El Hamma",
    "Ensigha",
    "Tamza",
    "Ain Touila",
    "M'toussa",
    "Bouhmama",
    "El Oueldja",
    "M'sara",
    "Chechar"
  ],
  "41": [
    "Souk Ahras",
    "Ain Soltane",
    "Sedrata",
    "Hanencha",
    "Machroha",
    "Ain Zana",
    "Ouled Driss",
    "Terraguelt",
    "Oum El Adhaim",
    "Oued Kebrit",
    "Tiffech",
    "Ragouba",
    "Drea",
    "Taoura",
    "Zaarouria",
    "Haddada",
    "Khedara",
    "Ouled Moumen",
    "Merahna",
    "Ouillen",
    "Sidi Fredj",
    "Bir Bouhouche",
    "Safel El Ouiden",
    "Khemissa",
    "M'daourouche",
    "Zouabi"
  ],
  "42": [
    "Hadjout",
    "Merad",
    "Menaceur",
    "Aghbal",
    "Nador",
    "Sidi-Amar",
    "Gouraya",
    "Messelmoun",
    "Cherchell",
    "Hadjret Ennous",
    "Sidi Ghiles",
    "Damous",
    "Larhat",
    "Fouka",
    "Ain Tagourait",
    "Bou Haroun",
    "Bou Ismail",
    "Khemisti",
    "Ahmer El Ain",
    "Bourkika",
    "Douaouda",
    "Sidi Rached",
    "Attatba",
    "Chaiba",
    "Kolea",
    "Sidi Semiane",
    "Tipaza",
    "Beni Mileuk"
  ],
  "43": [
    "El Mechira",
    "El Ayadi Barbes",
    "Ain Beida Harriche",
    "Tassala Lematai",
    "Terrai Bainen",
    "Amira Arres",
    "Tassadane Haddada",
    "Minar Zarza",
    "Sidi Merouane",
    "Chigara",
    "Hamala",
    "Grarem Gouga",
    "Tiberguent",
    "Rouached",
    "Derrahi Bousselah",
    "Zeghaia",
    "Oued Endja",
    "Ahmed Rachedi",
    "Tadjenanet",
    "Ain Mellouk",
    "Ouled Khalouf",
    "Benyahia Abderrahmane",
    "Teleghma",
    "Oued Seguen",
    "Oued Athmenia",
    "Ain Tine",
    "Chelghoum Laid",
    "Yahia Beniguecha",
    "Ferdjioua",
    "Sidi Khelifa",
    "Mila",
    "Bouhatem"
  ],
  "44": [
    "Khemis-Miliana",
    "Sidi-Lakhdar",
    "Ain-Benian",
    "Ain-Torki",
    "Hammam-Righa",
    "Bourached",
    "Hoceinia",
    "Djelida",
    "Arib",
    "Djemaa Ouled Cheikh",
    "El-Amra",
    "El-Attaf",
    "Tiberkanine",
    "Ain-Bouyahia",
    "El-Abadia",
    "Tacheta Zegagha",
    "Birbouche",
    "Djendel",
    "Ben Allal",
    "Oued Chorfa",
    "Boumedfaa",
    "Ain-Lechiakh",
    "Ain-Soltane",
    "Oued Djemaa",
    "El-Maine",
    "Rouina",
    "Zeddine",
    "Bir-Ould-Khelifa",
    "Bordj-Emir-Khaled",
    "Tarik-Ibn-Ziad",
    "Bathia",
    "Belaas",
    "Hassania",
    "Ain-Defla",
    "Miliana",
    "Mekhatria"
  ],
  "45": [
    "Tiout",
    "Moghrar",
    "Asla",
    "Kasdir",
    "Makmen Ben Amar",
    "Ain Sefra",
    "Mecheria",
    "El Biodh",
    "Ain Ben Khelil",
    "Naama",
    "Djenienne Bourezg",
    "Sfissifa"
  ],
  "46": [
    "Sidi Boumediene",
    "Tamzoura",
    "Chaabat El Ham",
    "El Maleh",
    "Ouled Kihal",
    "Chentouf",
    "Terga",
    "Oued Sebbah",
    "El Amria",
    "Hassi El Ghella",
    "Ouled Boudjemaa",
    "Aghlal",
    "Ain Kihal",
    "Ain Tolba",
    "Aoubellil",
    "Beni Saf",
    "Hassasna",
    "Emir Abdelkader",
    "Sidi Safi",
    "Oulhaca El Gheraba",
    "Sidi Ouriache",
    "Ain El Arbaa",
    "El Messaid",
    "Oued Berkeche",
    "Sidi Ben Adda",
    "Ain Temouchent",
    "Bouzedjar",
    "Hammam Bou Hadjar"
  ],
  "47": [
    "Dhayet Bendhahoua",
    "Mansoura",
    "El Atteuf",
    "Bounoura",
    "Zelfana",
    "El Guerrara",
    "Sebseb",
    "Metlili",
    "Berriane",
    "Ghardaia"
  ],
  "48": [
    "El-Guettar",
    "Ouled Aiche",
    "Beni Dergoun",
    "Dar Ben Abdelah",
    "Zemmoura",
    "Djidiouia",
    "Hamri",
    "Belaassel Bouzagza",
    "El-Matmar",
    "Sidi Khettab",
    "Sidi M'hamed Benaouda",
    "Ain-Tarek",
    "Had Echkalla",
    "El Ouldja",
    "Mazouna",
    "Ain Rahma",
    "Kalaa",
    "Sidi Saada",
    "Yellel",
    "Souk El Had",
    "Mendes",
    "Oued Essalem",
    "Sidi Lazreg",
    "Ammi Moussa",
    "Ouarizane",
    "Merdja Sidi Abed",
    "Ouled Sidi Mihoub",
    "Bendaoud",
    "Oued-Rhiou",
    "El Hassi",
    "Sidi M'hamed Benali",
    "Mediouna",
    "Beni Zentis",
    "Oued El Djemaa",
    "Lahlef",
    "Relizane",
    "El H'madna",
    "Ramka"
  ],
  "49": [
    "Tinerkouk",
    "Timimoun",
    "Ouled Said",
    "Metarfa",
    "Talmine",
    "Ouled Aissa",
    "Charouine",
    "Aougrout",
    "Deldoul",
    "Ksar Kaddour"
  ],
  "50": [
    "Timiaouine",
    "Bordj Badji Mokhtar"
  ],
  "51": [
    "Ras El Miad",
    "Besbes",
    "Sidi Khaled",
    "Doucen",
    "Chaiba",
    "Ouled Djellal"
  ],
  "52": [
    "Beni-Abbes",
    "Tamtert",
    "Igli",
    "El Ouata",
    "Ouled-Khodeir",
    "Kerzaz",
    "Timoudi",
    "Ksabi",
    "Beni-Ikhlef"
  ],
  "53": [
    "Inghar",
    "Ain Salah",
    "Foggaret Ezzoua"
  ],
  "54": [
    "Tin Zouatine",
    "Ain Guezzam"
  ],
  "55": [
    "Temacine",
    "Sidi Slimane",
    "Megarine",
    "Nezla",
    "Blidet Amor",
    "Tebesbest",
    "Touggourt",
    "Taibet",
    "El Alia",
    "El-Hadjira",
    "Benaceur",
    "M'naguer",
    "Zaouia El Abidia"
  ],
  "56": [
    "Djanet",
    "Bordj El Haouass"
  ],
  "57": [
    "Oum Touyour",
    "Sidi Amrane",
    "M'rara",
    "Djamaa",
    "Tenedla",
    "El-M'ghaier",
    "Still",
    "Sidi Khelil"
  ],
  "58": [
    "El Meniaa",
    "Hassi Gara",
    "Hassi Fehal"
  ],
  "59": [
    "El Beidha",
    "Gueltat Sidi Saad",
    "Brida",
    "Ain Sidi Ali",
    "Hadj Mechri",
    "Taouiala",
    "El Ghicha",
    "Sebgag",
    "Sidi Bouzid",
    "Oued Morra",
    "Oued M'zi",
    "Aflou"
  ],
  "60": [
    "Brezina",
    "Ghassoul",
    "Labiodh Sidi Cheikh",
    "Boussemghoun",
    "Cheguig",
    "Chellala",
    "Arbaouat"
  ],
  "61": [
    "Sidi Djillali",
    "Bouihi",
    "El Gor",
    "El Aricha"
  ],
  "62": [
    "Djemorah",
    "Branis",
    "El Outaya",
    "El Kantara",
    "Ain Zaatout"
  ],
  "63": [
    "Seggana",
    "Tilatou",
    "Barika",
    "Bitam",
    "M Doukal",
    "Azil Abedelkader",
    "Djezzar",
    "Ouled Ammar"
  ],
  "64": [
    "Sidi Hadjeres",
    "Bou Saada",
    "El Hamel",
    "Oulteme",
    "Benzouh",
    "Ouled Sidi Brahim",
    "Sidi Ameur",
    "Tamsa",
    "Ben Srour",
    "Mohamed Boudiaf",
    "Ouled Slimane",
    "Zarzour",
    "Ain El Melh",
    "Ain Fares",
    "Ain Rich",
    "Bir Foda",
    "Sidi M'hamed",
    "Medjedel",
    "Menaa",
    "Slim",
    "Maadid",
    "M'tarfa",
    "Maarif"
  ],
  "65": [
    "Ferkane",
    "Negrine",
    "El Ogla El Malha",
    "Bir-El-Ater"
  ],
  "66": [
    "Ouled Hellal",
    "Ksar El Boukhari",
    "M'fatha",
    "Saneg",
    "Bouaiche",
    "Boughzoul",
    "Chabounia",
    "Boghar",
    "Ain Boucif",
    "El Ouinet",
    "Kef Lakhdar",
    "Ouled Emaaraf",
    "Sidi Demed",
    "Ain Ouksir",
    "Chelalet El Adhaoura",
    "Cheniguel",
    "Tafraout",
    "Aziz",
    "Derrag",
    "Oum El Djellil",
    "Ouled Antar"
  ],
  "67": [
    "Ksar Chellala",
    "Serghine",
    "Zmalet El Emir Abdelkade",
    "Bougara",
    "Hamadia",
    "Rechaiga"
  ],
  "68": [
    "Had Sahary",
    "Bouira Lahdab",
    "Ain Fekka",
    "Sidi Laadjel",
    "Hassi Fedoul",
    "El Khemis",
    "Birine",
    "Guernini",
    "Ain Oussera",
    "Benhar"
  ],
  "69": [
    "Selmana",
    "Sed Rahal",
    "Messaad",
    "Guettara",
    "Deldoul",
    "Oum Laadham",
    "Faidh El Botma",
    "Amourah"
  ]
};
